### ISSUE TITLE
View not taken from base theme (OSOE-529)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Hosting-Media-Theme#30]
When using The Blog Theme as a base theme for [my media theme](https://github.com/Piedone/DotNest-Sites/tree/dev-piedone/src/Themes/LettersFromFiume.Theme) I noticed that the search page looks really bad:

![image](https://user-images.githubusercontent.com/1976647/211380635-427750c0-8622-4ac3-ac67-7fcfa0578fc9.png)

Note that the menu is there but invisible (white on white) unless highlighted like this. The problem is, that the `Header` zone doesn't get filled with [what the `Search` override defines in The Blog Theme](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Themes/TheBlogTheme/Views/Shared/Search.liquid#L1-L17).

My first idea was that [this limitation](https://github.com/Lombiq/Hosting-Media-Theme#:~:text=Folders%20within%20the%20Views%20folder%20are%20not%20supported.%20It%20also%20means%20that%20MVC%20views%20can%27t%20be%20overridden%20or%20custom%20shape%20harvesters%20can%27t%20be%20used.) has something to do with this. But looking at the code briefly, I couldn't pinpoint anything obvious. Rather, our base them handling is perhaps an issue: `BaseTheme` is just a dependency for themes, there's nothing else special about defining it. So, our approach of adding it as such in `ExtensionManagerDecorator` should work. However, there's something clearly missing since defining a base theme directly in Media theme (i.e. `BaseTheme = "TheBlogTheme"`) works:

![image](https://user-images.githubusercontent.com/1976647/211381140-003ee101-8972-4abd-b4db-c86d4b0cf41d.png)

I understand that I can't override views form my media theme, but views from a base theme should properly be applied. Other shape templates, i.e. Liquid files form the _Views_ folder of The Blog Theme get applied.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-529)

**Comment by Piedone** [comment]
Do you have any hints by chance, @barthamark?

**Comment by barthamark** [comment]
> Do you have any hints by chance, @barthamark?

Any views from the base theme (i.e., anything outside media theme) should work. I'm not sure why it doesn't happen, though, from the top of my head. 🫤

**Comment by wAsnk** [comment]
Fixed in https://github.com/Lombiq/Hosting-Media-Theme/pull/33

**Comment by wAsnk** [comment]
@davidpuplava the original bug still persists

**Comment by davidpuplava** [comment]
> @davidpuplava the original bug still persists

Ok I’ll take a look

**Comment by wAsnk** [comment]
> Ok I’ll take a look

Thank you!

**Comment by barthamark** [comment]
Hey guys, I might've misunderstood something here. To clarify, you can override everything that you would be able to override using Orchard Core's Templates feature; simply because it's using the same extension point. So AFAIK [this file](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Themes/TheBlogTheme/Views/Shared/Search.liquid) can't be overriden.

**Comment by Piedone** [comment]
It's not about overriding, but rather, that view form the base theme is not taking effect.

**Comment by davidpuplava** [comment]
> It's not about overriding, but rather, that view form the base theme is not taking effect.

This is what I understand the issue to be. Before #33, I reproduced the issue by 
1. Creating a new tenant with TheBlog theme,
2. Ran recipes for Lucene Search and Query to get the /search form page
3. Observed that the tenant's /search page looked as expected with the header section with the image
4. Then made the MediaTheme the current theme
5. On AdminUI's Configuration->Media Theme page, set the Base Theme to "The Blog Theme"
6. Observed the tenant's /search page was missing the astronaut image and the header section altogether
7. After the fix in #33, navigating to the /search page using TheMediaTheme configured to use "The Blog Theme" as the base, I observed the header as expected

I pulled the latest dev branch and it works using the above steps. @wAsnk or @Piedone is there a different set of steps to reproduce the issue?

**Comment by wAsnk** [comment]
In the 2nd point what recipes are you running exactly and do you do anything else?

**Comment by wAsnk** [comment]
I tried your steps and the result is this for me:
![image](https://user-images.githubusercontent.com/19938236/216321398-0c2f07ba-32d4-4b5c-ae24-9631971ba333.png)

**Comment by Piedone** [comment]
The fix works in OSOCE but didn't work on DotNest because actually not the latest version of the submodule was pulled in... So, now https://lettersfromfiume.com/Search works too!

Sorry about the false alarm.

**Comment by wAsnk** [comment]
Yeah, sorry that was probably a misclick on my side then...
