### ISSUE TITLE
Deployer runs before Node.js Extensions compiles the assets (OSOE-674)

### ISSUE THREAD

**Issue by barthamark** [Lombiq/Hosting-Media-Theme#43]
Deployer runs before Node.js Extensions compiles the assets so it won't create the necessary Media steps in the Media Theme recipe. The workaround is to commit the content of wwwroot.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-674)

**Comment by Piedone** [comment]
How do you run the Deployer?

**Comment by barthamark** [comment]
I'm importing the Lombiq.Hosting.MediaTheme.Targets.props and targets files in the theme's csproj. It executes the following target before build:
`
  <Target Name="RunMediaThemeDeployer" BeforeTargets="BeforeBuild">
    <Exec Command="dotnet media-theme-deploy --path . --base-id $(MediaThemeBaseId) --clear true --deployment-path $(DeploymentFolder) --deployment-file-name $(MediaThemeRecipeFileName)"/>
  </Target>
`

**Comment by Piedone** [comment]
This is the issue with that project then. The Deployer doesn't have anything to do with compilation. You need to change that project to execute the Deployer at a better time in the build pipeline.
